shared_examples "Add Non Person Things: Verify All Things Searchable" do
  it "Verify all roles are searchable" do
  end

  it "No need to log in" do
    $browser.navigate.to vivo_url("/")
    expect($browser.title).to eq("VIVO")
  end

  it "Verify search results for VIVO" do
    $browser.find_element(:name, "querytext").clear
    $browser.find_element(:name, "querytext").send_keys("primates")
    $browser.find_element(:xpath, ".//input[@value='Search']").click
    expect($browser.title).to eq("Search for 'primates'")
    $browser.find_element(:link_text, "people")
    $browser.find_element(:link_text, "activities")
    $browser.find_element(:link_text, "courses")
    $browser.find_element(:link_text, "events")
    $browser.find_element(:link_text, "organizations")
    $browser.find_element(:link_text, "equipment")
    $browser.find_element(:link_text, "research")
    $browser.find_element(:link_text, "locations")
    $browser.find_element(:link_text, "Primates in the Wild")
    expect(browser_page_text).to include("Primates in the Wild Performance")
    $browser.find_element(:link_text, "Introduction to Primates")
    expect(browser_page_text).to include("Introduction to Primates Course")
    $browser.find_element(:link_text, "Primates-r-us")
    expect(browser_page_text).to include("Primates-r-us Company")
    $browser.find_element(:link_text, "Primate Happenings")
    expect(browser_page_text).to include("Primate Happenings Blog Posting")
    $browser.find_element(:link_text, "Primate Info")
    expect(browser_page_text).to include("Primate Info Database")
    $browser.find_element(:link_text, "Primate Health")
    expect(browser_page_text).to include("Primate Health Concept")
    $browser.find_element(:link_text, "Primate Quad")
    expect(browser_page_text).to include("Primate Quad Geographic Location")
    $browser.find_element(:link_text, "Primate Feeder")
    expect(browser_page_text).to include("Primate Feeder Equipment")
    $browser.find_element(:link_text, "Primate Diet")
    expect(browser_page_text).to include("Primate Diet Concept")
    $browser.find_element(:link_text, "Primate College of America")
    expect(browser_page_text).to include("Primate College of America College")
    $browser.find_element(:link_text, "Primate Health Talks")
    expect(browser_page_text).to include("Primate Health Talks Seminar Series")
    $browser.find_element(:link_text, "Primate Research Laboratory")
    expect(browser_page_text).to include("Primate Research Laboratory Laboratory")
    $browser.find_element(:link_text, "Portable Primate Habitat")
    expect(browser_page_text).to include("Portable Primate Habitat Equipment")
    $browser.find_element(:link_text, "Primate Elderly Care")
    expect(browser_page_text).to include("Primate Elderly Care Grant")
    $browser.find_element(:link_text, "Introduction to Primate Health")
    expect(browser_page_text).to include("Introduction to Primate Health Course")
    $browser.find_element(:link_text, "Primate Health and Fitness")
    expect(browser_page_text).to include("Primate Health and Fitness Invited Talk")
    $browser.find_element(:link_text, "Primate University of America")
    expect(browser_page_text).to include("Primate University of America University")
    $browser.find_element(:link_text, "Primate Colleges of the World")
    expect(browser_page_text).to include("Primate Colleges of the World Consortium")
    $browser.find_element(:link_text, "Primate Health Check")
    expect(browser_page_text).to include("Primate Health Check Event")
    $browser.find_element(:link_text, "Primate Health Conference")
    expect(browser_page_text).to include("Primate Health Conference Conference")
    $browser.find_element(:link_text, "Primate Heart Health")
    expect(browser_page_text).to include("Primate Heart Health Service")
    $browser.find_element(:link_text, "New Primate Students")
    expect(browser_page_text).to include("New Primate Students Workshop")
    $browser.find_element(:link_text, "Primate Habitat Research Grant")
    expect(browser_page_text).to include("Primate Habitat Research Grant Grant")
    $browser.find_element(:link_text, "Primate Memorial Building")
    expect(browser_page_text).to include("Primate Memorial Building Building")
    $browser.find_element(:link_text, "Primate Student of the Year")
    expect(browser_page_text).to include("Primate Student of the Year Award or Honor")
    $browser.find_element(:link_text, "2").click
    expect($browser.title).to eq("Search for 'primates'")
    $browser.find_element(:link_text, "Best Primate College")
    expect(browser_page_text).to include("Best Primate College Award or Honor")
    $browser.find_element(:link_text, "Primate History Library")
    expect(browser_page_text).to include("Primate History Library Library")
    $browser.find_element(:link_text, "Primate Survival Planning Grant")
    expect(browser_page_text).to include("Primate Survival Planning Grant Grant")
    $browser.find_element(:link_text, "Primate College of New York")
    expect(browser_page_text).to include("Primate College of New York College")
    $browser.find_element(:link_text, "Primate Research Lab Room 123")
    expect(browser_page_text).to include("Primate Research Lab Room 123 Facility")
    $browser.find_element(:link_text, "Animal Health")
    expect(browser_page_text).to include("Animal Health Concept")
    $browser.find_element(:link_text, "Ape Health")
    expect(browser_page_text).to include("Ape Health Concept")
    $browser.find_element(:link_text, "Elderly Care")
    expect(browser_page_text).to include("Elderly Care Concept")
    $browser.find_element(:link_text, "Jane Memorial Building")
    expect($browser.find_element(:xpath, ".//div[@id='wrapper-content']/div/ul/li[9]/span").text).to eq("Building")
    $browser.find_element(:link_text, "exact:http://primatehealthintro.cornell.edu")
    expect(browser_page_text).to include("http://primatehealthintro.cornell.edu Webpage")
    $browser.find_element(:link_text, "Human and Ape Brain Comparison")
    expect(browser_page_text).to include("Human and Ape Brain Comparison Human Study")
    $browser.find_element(:link_text, "Person, Polly")
    expect($browser.find_element(:xpath, ".//div[@id='wrapper-content']/div/ul/li[12]/span").text).to eq("Person")
    $browser.find_element(:link_text, "Gorilla Moving Company")
    expect(browser_page_text).to include("Gorilla Moving Company Transport Service")
    $browser.find_element(:link_text, "PHC Proceedings")
    expect(browser_page_text).to include("PHC Proceedings Proceedings")
    $browser.find_element(:link_text, "State Fair Park")
    expect($browser.find_element(:xpath, ".//div[@id='wrapper-content']/div/ul/li[15]/span").text).to eq("Facility")
    $browser.find_element(:link_text, "USA222333444555")
    expect(browser_page_text).to include("USA222333444555 Patent")
    $browser.find_element(:link_text, "Africa")
    expect(browser_page_text).to include("Africa Continent Transnational Region")
    $browser.find_element(:link_text, "Kenya")
    expect(browser_page_text).to include("Kenya Country")
    $browser.find_element(:link_text, "Home").click
    expect($browser.title).to eq("VIVO")
    end
  end
